### ISSUE TITLE
Feature Request: Boerderij uppercase

### ISSUE THREAD

**Issue by TheCad** [rtgschepers/BiteFight-extension#1]
<img width="179" alt="image" src="https://github.com/rtgschepers/BiteFight-extension/assets/2212054/d681db5e-2b6b-4358-beb0-5cecd89c0b4f">

Ik heb een feature request!!!

**Comment by rtgschepers** [comment]
This has been solved in [6e49a7f](https://github.com/rtgschepers/BiteFight-extension/commit/6e49a7fc6c8455d732078cb47ec593bdb082fdb8)

**Comment by TheCad** [comment]
+1
